name: Status Checks

on:
  push:
    branches: [ master ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - run: yarn

  run-jest:
    runs-on: ubuntu-latest
    needs: [ install-dependencies ]
    steps:
      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: yarn test
