name: Status Checks

on:
  push:
    branches: [ master ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  run-jest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: yarn 

      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: yarn test